# Generated by Django 3.1 on 2020-08-20 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghost', '0002_post_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='score',
        ),
    ]
