# Generated by Django 3.1 on 2020-08-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghost', '0003_remove_post_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='down_vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='up_vote',
            field=models.IntegerField(default=0),
        ),
    ]
